export default {
    INITIAL_SCREEN:'initialScreen',
    LOGIN:'login',
    OTP_VERIFICATION:'otpVerificaion',
    BROWSE:'Browse',
    HOME:'Home',
    FEED:'Feed Page',
    REVIEWS:'Reviews',
    TRAILER:'Trailers',
    NOTIFICATION:'notification',
    TAB_ROUTES:'tabRoutes',
    DRAWER_ROUTES:'drawerroutes',
    MOVIES_LIST:'movielist',
    MOVIE_REVIEW:'Moviereview',
    MOVIE_FEED:'Moviefeed',
    GROUP_PAGE:'grouppage',
    INTERNATIONAL_MOVIELIST:'internationalmovielist',
    NEW_GROUP:'newgroup',
    WARRIORS:'warriors'
}